"""empty message

Revision ID: 8f61e361e6c8
Revises: 
Create Date: 2020-08-13 22:54:44.765191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f61e361e6c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('bord_name', sa.String(length=128), nullable=True),
    sa.Column('creator_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borda_bord_name'), 'borda', ['bord_name'], unique=True)
    op.create_index(op.f('ix_borda_creator_name'), 'borda', ['creator_name'], unique=False)
    op.create_index(op.f('ix_borda_timestamp'), 'borda', ['timestamp'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.Column('bord_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bord_id'], ['borda.bord_name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_borda_timestamp'), table_name='borda')
    op.drop_index(op.f('ix_borda_creator_name'), table_name='borda')
    op.drop_index(op.f('ix_borda_bord_name'), table_name='borda')
    op.drop_table('borda')
    # ### end Alembic commands ###
